### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by BeeryShklar**
A new logo.
Continuation of #142 .

Changed everything in `images` folder, hope that's all i needed to change.

logo-256x256

### CODE REVIEW

**Comment by lauverityhill** [comment]
First all, great logo!

I tested this, but it seems you missed changing the "logo.ico" found in `workspacer-master\src\workspacer\logo.ico`.

I had to convert the PNGs to the ICO format. After that, it worked. Though I just used a random online image converter.

**Comment by BeeryShklar** [comment]
I will change it...
By the way I did have an ICO file but it was in `src/images` and I also used an online converter for it.

**Comment by rickbutton** [comment]
there are also images in the "docs" folder, which is used for the website, so feel free to update those as well. The website will autodeploy when this is merged into master.

**Comment by BeeryShklar** [comment]
@lauverityhill and @rickbutton can you review my changes?

**Review by josteink — APPROVED** [review]
Built, ran, did a visual inspection.

All looks good to me!

**Pull request merged**
