### PR TITLE
New Layouts (Golden Ratio & Vertical List)

### PR DESCRIPTION
**Pull request by haoxiangliew**
Credits to Fusion and ianelletson for initial code

These configurations have been tested on my setup, and I haven't encountered any bugs

### CODE REVIEW

**Comment by josteink** [comment]
@rickbutton : This PR is not really my stuff... Would you care look into it?

**Review by N1x0 — CHANGES_REQUESTED** [review]
Overall I like the dwindle layout engine (Golden Ratio), however I am not really convinced by the Vertical List one. It has some weird behaviour. Also there is an existing `VertLayoutEngine` so I am not sure how much value an additional one brings. If people like it I don't see an issue to incorporate it but it really should have a different name...

Other comments
- A few typo's and minor issues
- Naming of things is a bit weird overall

**Comment by haoxiangliew** [comment]
Thanks for the review @N1x0 , I'll try to get the commits in asap

But I didn't know there was a `VertLayoutEngine` in workspacer? It's not in /src/workspacer.Shared/layouts

**Comment by N1x0** [comment]
You're very welcome @haoxiangliew , sorry it took so long for you to get some comments on what I think is an overall nice addition. Just FYI somewhere in the code there's a missing `_` in one of the variables, I forgot where exactly but if you try to compile it'll show right up so maybe check for that as well

Oh and the `VertLayoutEngine` is part of the `PaneLayoutEngine` which also includes the `HorzLayoutEngine` class, so there's basically two layouts classes in the single file which is probably why you didn't see it 😄.

**Comment by josteink** [comment]
The build for this PR fails because of a missing semicolon. 

From the CI:

```

D:\a\workspacer\workspacer\src\workspacer.Shared\Layout\DwindleLayoutEngine.cs(109,34): error CS1002: ; expected [D:\a\workspacer\workspacer\src\workspacer.Shared\workspacer.Shared.csproj]
12
    0 Warning(s)
13
    1 Error(s)

```

Could you fix that? 🙂

**Comment by haoxiangliew** [comment]
Sorry I don't run workspacer on Windows anymore, so I'm unable to test the configuration on my side. I will keep this PR open if anyone else would like to work on these layouts, or feel free to close it.

**Comment by josteink** [comment]
Thanks for the quick feedback @haoxiangliew.

Considering that currently this PR doesn't build, and that you yourself no longer have any interest in it, I'm going to close it.

Sorry for being slow to process this one :disappointed:

**Pull request closed without merging**
