### PR TITLE
Fixed Bar sizing issue

### PR DESCRIPTION
**Pull request by NeoNlAmp3**
Issue mentioned in [https://github.com/rickbutton/workspacer/issues/169](url)

### CODE REVIEW

**Comment by josteink** [comment]
I really can't see why this change should fix your issues. And I kinda don't like fixing bugs by making changes which in theory shouldn't ... change things. Basically I don't like magic :smile: 

On the other hand I can't see how this change can cause any other negative adverse effects, so unless anyone else objects, I'm OK with merging this.

**Comment by NeoNlAmp3** [comment]
Yes I was also quite confused.
But this morning I realized that there is a gap in Y direction.
So I checked what is happening again.

The Gap
Scaling
Scaling2
Monitor Settup

It hit me when I saw 24 to 30 => 30/24 = 1,25 which is the Windows scaling of Monitor 1 and 3. Monitor 2 is the only one at a scaling on 100%.
Basically this.Location = new Point(....) will cause some scaling after the width and height are set and change them to x/125

I don't know how this could be prevented as Point is a class inside System.Windows.Forms.Control and I can't debug into it to see who is the baddy

**Comment by NeoNlAmp3** [comment]
I updated the Branch.

Now the size will be overwritten after the scaling happened. It's not a good solution an quite ugly in my opinions but it works so far. 
Maybe some one else can test the scaling behavior to confirm the issue/fix.

**Comment by josteink** [comment]
I notice you set the `Height` only, and then later set both `Height` and `Width`.

Is that intentional or a slip?

**Comment by NeoNlAmp3** [comment]
It's intentional, if the Height is not set before the Location is assigned with Point, the bar will slide up by the difference of the scaling. So in my case the bar was 6px up outside of the screen.
So the height must be set before the scaling happens, then the scaling does it stuff and then I reset the height to the intended value.

**Review by josteink — APPROVED** [review]

**Comment by josteink** [comment]
Oh well. Consider it merged then :smile:

**Pull request merged**
