### PR TITLE
Override update branch with settings.yaml

### LINKED ISSUE #153: Automatic Update issues
So workspacer should have automatic updates which is provided through the `AutoUpdater.NET` `NuGet` package. However I'm not sure if that is working as intended. 

The following is implemented in `\workspacer\src\workspacer\Program.cs`:

```csharp
#if BRANCH_unstable
            var branch = "unstable";
#elif BRANCH_stable 
            var branch = "stable";
#else
            string branch = null;
#endif
            if (branch != null)
            {
                var xmlUrl = $"https://workspacer.blob.core.windows.net/installers/{branch}.xml";

                AutoUpdater.ApplicationExitEvent += QuitForUpdate;

                System.Timers.Timer timer = new System.Timers.Timer(1000 * 60 * 60);
                timer.Elapsed += (s, e) =>
                {
                    AutoUpdater.Start(xmlUrl);
                };
                timer.Enabled = true;
                AutoUpdater.Start(xmlUrl);
            }
```

Maybe I didn't look carefully enough but I couldn't find a preprocessor directive for either `BRANCH_unstable` or `BRANCH_stable` meaning the check for updates never happens because `branch`will always evaluate to `null`. I tested this by editing the Assembly Version and the update does trigger correctly when the directives are present. I still don't quite understand the purpose of the 1hr timer though...

A second potential issue is that the user has no way of configuring this behaviour without going into the source files. I think it'd be nice to have this accessible through the config file instead. 

A a side note would implementing checksums for the downloads be possible? Would be nice if there's a way verify the integrity of the download prior to execution.

Happy to write something up for this if there's interest to have this feature.

### PR DESCRIPTION
**Pull request by sitiom**
Resolves #153.

You can now simply override or switch from the defined branch with your own by setting `~/.workspacer/settings.yaml` with:
```yaml
branch: stable
# or
branch: unstable
```

Edit:
Added `none`  as an option to disable auto-update. This would be useful for installing from [scoop](https://github.com/lukesampson/scoop-extras/pull/5278).

### CODE REVIEW

**Comment by rickbutton** [comment]
We already have an optional config file where you can write custom C# to change settings. Would it make more sense to just allow you to write a line of code in that file that overrides the update branch?

**Comment by sitiom** [comment]
> We already have an optional config file where you can write custom C# to change settings. Would it make more sense to just allow you to write a line of code in that file that overrides the update branch?

Makes sense.

**Comment by sitiom** [comment]
Now you could do:

```cs
context.Branch = Branch.Stable;
// or
context.Branch = Branch.Unstable;
// or disable updates
context.Branch = Branch.None;
```

**Comment by sitiom** [comment]
Closing this in favor of #156.

**Pull request closed without merging**
